
# For documentation of generating secrets with kustomize, see this documentation page:
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md.

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: laravel-env
data:
  APP_DEBUG: dHJ1ZQ== # true
  APP_ENV: ZGV2ZWxvcG1lbnQ= # development
  APP_KEY: YmFzZTY0OjJrRHpxSldvSUJaNzAxTmNCdnZXdDFKbVF1WEZwcjBCSlF1U0ZiY291c0E9Cg== 
